# Generated by Django 4.2.6 on 2023-11-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-published_date"],
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.RenameField(
            model_name="news", old_name="pub_date", new_name="published_date",
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(verbose_name="Контент"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок"),
        ),
    ]
