# Generated by Django 4.1.2 on 2023-10-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание ресторана"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="restaurant_images/",
                verbose_name="Изображение ресторана",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="website",
            field=models.URLField(blank=True, verbose_name="Веб-сайт"),
        ),
    ]
