# Generated by Django 4.2.6 on 2023-11-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_customuser_birth_date_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзины"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterModelOptions(
            name="restaurantinfo",
            options={
                "verbose_name": "Информация о ресторане",
                "verbose_name_plural": "Информация о ресторанах",
            },
        ),
    ]
